name: Site
on: 
  push:
    paths:
      - 'build/*'

jobs:
  build:
    name: Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit and push 
        run: |
          date > build/action-test.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

