---
name: Site
on:
  push:
    paths:
      - 'index/*'
      - 'build/**'
      - '.github/workflows/*'
      - 'xml/*'
jobs:
  build:
    name: Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          php build/build.php
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Le bot a regénéré le site et les stats" || echo "Le site n’a pas changé"
          git push || echo "Le site n’a pas changé"
